//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string FileUrl { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public int OSPlatformRef { get; set; }
        public bool IsTop { get; set; }
    
        public virtual OSPlatform OSPlatform { get; set; }
    }
}
