//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsnApp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }
        public string InfoUrlFacebook { get; set; }
        public string InfoUrlTwitter { get; set; }
        public int Developer { get; set; }
        public string SiteUrl { get; set; }
        public string Icon { get; set; }
        public int CategoryRef { get; set; }
        public bool MarkForDeletion { get; set; }
        public string OSPlatforms { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
    }
}
