//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications_OSPlatforms
    {
        public Applications_OSPlatforms()
        {
            this.OSVersions = new HashSet<OSVersion>();
        }
    
        public int Id { get; set; }
        public int ApplicationRef { get; set; }
        public int OSPlatformRef { get; set; }
        public string Version { get; set; }
        public bool VersionVariesWithDevice { get; set; }
        public string Permissions { get; set; }
        public decimal Size { get; set; }
        public bool SizeVariesWithDevice { get; set; }
        public string MarketURL { get; set; }
        public double PriceUSD { get; set; }
        public double PriceEUR { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public bool IsVisible { get; set; }
        public bool MarkForDeletion { get; set; }
        public string Video { get; set; }
    
        public virtual OSPlatform OSPlatform { get; set; }
        public virtual ICollection<OSVersion> OSVersions { get; set; }
    }
}
