//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.Guid UserRef { get; set; }
        public string CommentText { get; set; }
        public System.DateTime PostedDate { get; set; }
        public int ApplicationRef { get; set; }
        public bool IsVisible { get; set; }
        public bool IsMarkAsSafe { get; set; }
        public bool IsSpam { get; set; }
        public bool IsInappropriateLanguage { get; set; }
        public bool IsPostedByDeveloper { get; set; }
        public bool IsPostedByAdmin { get; set; }
    }
}
