//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompareAppsBDEntities : DbContext
    {
        public CompareAppsBDEntities()
            : base("name=CompareAppsBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advertisement> Advertisements { get; set; }
        public DbSet<AppDeveloper> AppDevelopers { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Applications_OSPlatforms> Applications_OSPlatforms { get; set; }
        public DbSet<ApplicationsnApp> ApplicationsnApps { get; set; }
        public DbSet<BrandType> BrandTypes { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<ContentPage> ContentPages { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Favorite> Favorites { get; set; }
        public DbSet<GenderType> GenderTypes { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<OSPlatform> OSPlatforms { get; set; }
        public DbSet<OSVersion> OSVersions { get; set; }
        public DbSet<PhoneBrand> PhoneBrands { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Slider> Sliders { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<RegisteredUser> RegisteredUsers { get; set; }
    }
}
