//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPage
    {
        public int Id { get; set; }
        public string Alias { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Content { get; set; }
        public bool IsVisible { get; set; }
        public bool ShowInMenu { get; set; }
        public int Order { get; set; }
    }
}
