//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompareApps.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSVersion
    {
        public OSVersion()
        {
            this.Applications_OSPlatforms = new HashSet<Applications_OSPlatforms>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OSPlatformRef { get; set; }
        public int Order { get; set; }
        public bool IsVisible { get; set; }
        public bool MarkForDeletion { get; set; }
    
        public virtual OSPlatform OSPlatform { get; set; }
        public virtual ICollection<Applications_OSPlatforms> Applications_OSPlatforms { get; set; }
    }
}
